### PR TITLE
feat(Admin Component): Created Admin component, just a base component…

### LINKED ISSUE #81: Admin Console Component

### PR DESCRIPTION
**Pull request by KayPaint**
… no content

### CODE REVIEW

**Comment by KayPaint** [comment]
Good to review now!

~~WIP Branch~~

**Review by MShiers7 — COMMENTED** [review]
Line 52, 60, and 69 need to be plural.

**Comment by KayPaint** [comment]
Current Bugs:
- handleCategorySelect & handleActionSelect seem to 'lag' behind the input the user provides. Console loggings shows the value being provided to the setState is accurate though.
- Dynamic rendering issues with form fields, will address soon.
- Can't log in as Admin, so cant test if authentication testing works

**Comment by KayPaint** [comment]
With last commit:
- Added useEffects for ensuring re-render of selected category/action
- Refactored handleFormChange to be more efficient, and far less verbose
- Added necessary formData state reset at the end of handleSubmit, this ensures state is ready for new operation
- Added placeholder option tag for dropdowns, cleaner appearance
- Refactored dynamic rendering of input fields, now handles cases correctly
- Temporarily commented out the admin authorization

**Comment by KayPaint** [comment]
Admin is finally complete.

Closes #81

**Review by jhoolwerf — APPROVED** [review]

**Review by Remics89 — APPROVED** [review]

**Pull request merged**
